### ISSUE TITLE
kibana plugin support

### ISSUE THREAD

**Issue by hex2a** [rtib/puppet-kibana5#1]
please add support for installation/removal of kibana plugins, similar to lesaux-kibana4:

https://forge.puppet.com/lesaux/kibana4#plugins
https://github.com/lesaux/puppet-kibana4/blob/master/manifests/plugin.pp

**Comment by rtib** [comment]
That's a bit more tricky. I'm fond of a solution somewhat like https://forge.puppet.com/elasticsearch/elasticsearch#plugins but that needs to be implemented by a custom type provider.

**Comment by rtib** [comment]
Hence elastic-kibana was released, this module is obsolete, so this issue as well.
